
package:
  name: thor
  version: "{{ version }}"

source:
  git_url: "https://github.com/moeyensj/thor.git"
  git_tag: "v{{ version }}"

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools >= 45
    - setuptools_scm >= 6.0
    - wheel
  run:
    - python {{ python }}
    - astropy >= 5.3.1
    - astroquery
    - difi
    - healpy
    - jax
    - numpy
    - numba
    - pandas
    - pyarrow >= 13.0.0
    - pyyaml >= 5.1
    - quivr >= 0.7.1
    - ray-default
    - scikit-learn
    - scipy
    - spiceypy
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pre-commit

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

test:
  imports:
    - thor

about:
  home: https://github.com/moeyensj/thor
  license: BSD-3 Clause
  license_file: LICENSE.md
