version: "3.8"

services:
  thor:
    container_name: thor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".ipython:/root/.ipython/"
      - '.:/code'
      - ".docker_bash_history.txt:/root/.bash_history"
      - ".volumes:/opt/volumes/"
    tmpfs:
      - /dev/shm:size=8g
