[build-system]
requires = ["setuptools>=66", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "thor/version.py"
write_to_template = "__version__ = '{version}'"
