
name: docker - Build Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build
        run: docker build --load -t thor:$IMAGE_TAG .
      - name: Lint
        run: docker run -i thor:$IMAGE_TAG pre-commit run --all-files
      - name: Test
        if: always()
        run: docker run -i thor:$IMAGE_TAG pytest . --cov
