name: pdm - Build and Integration Test

on:
  schedule:
    # Run every day at 20:00 UTC
    - cron: '0 20 * * * '

jobs:
  build-integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pdm
        run: pip install pdm
      - name: Install Dependencies
        run: pdm install -G dev
      - name: Integration Tests
        run: pdm run pytest --benchmark-disable -m "integration"
