name: pdm - Build Lint Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pdm
        run: pip install pdm
      - name: Install Dependencies
        run: pdm install -G dev
      - name: Lint
        run: |
          pdm run ruff check ./src/thor
          pdm run black --check ./src/thor
          pdm run isort --check-only ./src/thor
      # - name: Type check
      #   run: pdm run mypy --strict ./src/thor
      - name: Test with coverage
        run: pdm run pytest --cov=thor --cov-report=xml --benchmark-disable
      - name: Coverage Report
        uses: coverallsapp/github-action@v2.0.0
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          path-to-lcov: coverage.xml
