name: pip - Build and Integration Test

on:
  schedule:
    # Run every day at 20:00 UTC
    - cron: '0 20 * * * '

jobs:
  build-lint-test-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -l {0}
    env:
      OORB_DATA: /tmp/oorb/data

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Install openorb dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gfortran liblapack-dev
          wget  -P /tmp/ https://storage.googleapis.com/oorb-data/oorb_data.tar.gz
          mkdir -p /tmp/oorb/
          tar -xvf /tmp/oorb_data.tar.gz -C /tmp/oorb/
      - name: Install Dependencies
        run: |
          pip install pip --upgrade
          pip install ".[dev]"
      - name: Integration Tests
        run: pdm test -k integration
