name: pip - Build and Integration Test

on:
  schedule:
    # Run every day at 20:00 UTC
    - cron: '0 20 * * * '

jobs:
  build-lint-test-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: "thor"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install openorb using conda
        run: conda install -c defaults -c conda-forge openorb --yes
      - name: Update OBSCODE.dat
        run: |
          cd $CONDA_PREFIX/share/oorb && ./updateOBSCODE
          cp OBSCODE.dat $CONDA_PREFIX/share/openorb/OBSCODE.dat
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Build and install
        run: pip install .[tests]
      - name: Integration Tests
        run: pytest . -m "integration"
